import header from './header.json.js';
import footer from './footer.json.js';

export default {
  'en': {
    'header': header.en,
    'footer': footer.en,
    'title': 'Jáquécastigo',
    'subtitle': 'Account your headaches',
    'monthLetters': {
      "01": "January",
      "02": "February",
      "03": "March",
      "04": "April",
      "05": "May",
      "06": "June",
      "07": "July",
      "08": "August",
      "09": "September",
      "10": "October",
      "11": "November",
      "12": "December",
    },
    'selectyear': 'Select year',
    'selectmonth': 'Select month',
    'year': 'Year',
  },
  'es': {
    'header': header.es,
    'footer': footer.es,
    'title': 'Jáquécastigo',
    'subtitle': 'Cuenta tus jaquecas',
    'monthLetters': {
      "01": "Enero",
      "02": "Febrero",
      "03": "Marzo",
      "04": "Abril",
      "05": "Mayo",
      "06": "Junio",
      "07": "Julio",
      "08": "Agosto",
      "09": "Septiembre",
      "10": "Octubre",
      "11": "Noviembre",
      "12": "Diciembre",
    },
    'selectyear': 'Selecciona un año',
    'selectmonth': 'Selecciona un mes',
    'year': 'Año',
  },
}