// import navigationMenu from './other.json.js';

import header from './header.json.js';
import footer from './footer.json.js';

export default {
  'en': {
    'header': header.en,
    'footer': footer.en,
    'formData': {
      'title': 'Jáquécastigo',
      'subtitle': 'Account your headaches',
      'notlogged': 'You are not logged in',
      'fechahora': 'Date and time',
      'editando': 'Editing',
      'gradodolor': 'Pain level',
      'mismoprocesoanterior': 'Same process as before',
      'molestias': 'Discomfort',
      'otrossintomas': 'Other symptoms',
      'medicacion': 'Medication',
      'duracion': 'Duration',
      'borrar': 'Delete',
      'guardar': 'Save',
      'cancel': 'Cancel',
      'units': 'hours',
      'yes': 'Yes',
      'no': 'No',
      'close': 'Close',
      'mensajeModalBorrar': 'Are you sure you want to delete this record?',
      'newEntry': 'New entry',
      'mensajeDatosGuardados': 'Data saved successfully',
      'contprocesoanterior': 'Continuation of previous process',
      'grupoMolestias': {
        'M1': 'Small eye discomfort',
        'M2': 'Eye discomfort',
        'M3': 'Intense eye discomfort',
        'M4': 'Very intense eye discomfort',
        'M5': 'Medium face discomfort',
        'M6': 'Intense medium face discomfort',
        'M7': 'Photophobia',
        'M8': 'Nausea',
      },
      'sinmolestias': 'No discomfort',
      'sinotros': 'No other symptoms',
      'sinmedicacion': 'No medication',
      'sinduracion': 'No defined duration',
      'grupoDolor': {
        'D0': 'Light pain',
        'D1': 'Stinging pain',
        'D2': 'Very stinging pain',
        'D3': 'Pain prevents normal life',
      },
      'select': 'Select',
      'fecha': 'Date',
      'grupoMenu': {
        'inicio': 'Home',
        'grafico': 'Annual Graph',
        'estadisticas': 'Statistics',
        'listado': 'List',
        'insertar': 'Insert Data',
        'acercade': 'About',
      },
      'monthLetters': {
        "01": "Jan",
        "02": "Feb",
        "03": "Mar",
        "04": "Apr",
        "05": "May",
        "06": "Jun",
        "07": "Jul",
        "08": "Aug",
        "09": "Sep",
        "10": "Oct",
        "11": "Nov",
        "12": "Dec",
      },
    },
  },
  'es': {
    'header': header.es,
    'footer': footer.es,
    'formData': {
      'title': 'Jáquécastigo',
      'subtitle': 'Contabiliza tus jaquecas',
      'notlogged': 'No has iniciado sesión',
      'fechahora': 'Fecha y hora',
      'editando': 'Editando',
      'gradodolor': 'Grado de dolor',
      'mismoprocesoanterior': 'Continuación proceso anterior',
      'molestias': 'Molestias',
      'otrossintomas': 'Otros síntomas',
      'medicacion': 'Medicación',
      'duracion': 'Duración',
      'borrar': 'Borrar',
      'guardar': 'Guardar',
      'cancel': 'Cancel',
      'units': 'horas',
      'yes': 'Sí',
      'no': 'No',
      'close': 'Cerrar',
      'mensajeModalBorrar': '¿Estás seguro de que quieres borrar este registro?',
      'newEntry': 'Nuevo registro',
      'mensajeDatosGuardados': 'Datos guardados correctamente',
      'contprocesoanterior': 'Continuacion proceso anterior',
      'grupoMolestias': {
        'M1': 'Pequeña molestia ojo',
        'M2': 'Molestia ojo',
        'M3': 'Molestia intensa ojo',
        'M4': 'Molestia muy intensa ojo',
        'M5': 'Molestia media cara',
        'M6': 'Molestia intensa media cara',
        'M7': 'Fotofobia',
        'M8': 'Nauseas',
      },
      'sinmolestias': 'Sin molestias',
      'sinotros': 'Sin otros síntomas',
      'sinmedicacion': 'Sin medicación',
      'sinduracion': 'Sin duración definida',
      'grupoDolor': {
        'D0': 'Dolor leve',
        'D1': 'Dolor punzante',
        'D2': 'Dolor muy punzante',
        'D3': 'Dolor impide hacer vida normal',
      },
      'select': 'Selecciona',
      'fecha': 'Fecha',
      'grupoMenu': {
        'inicio': 'Inicio',
        'grafico': 'Gráfico Anual',
        'estadisticas': 'Estadísticas',
        'listado': 'Listado',
        'insertar': 'Insertar Datos',
        'acercade': 'Acerca de',
      },
      'monthLetters': {
        "01": "Ene",
        "02": "Feb",
        "03": "Mar",
        "04": "Abr",
        "05": "May",
        "06": "Jun",
        "07": "Jul",
        "08": "Ago",
        "09": "Sep",
        "10": "Oct",
        "11": "Nov",
        "12": "Dic",
      },
      'currentYear': new Date().getFullYear(),
    }
  }
};
