import header from './header.json.js';
import footer from './footer.json.js';

export default {
  'en': {
    'header': header.en,
    'footer': footer.en,
    'title': 'Jáquécastigo',
    'subtitle': 'Account your headaches',
    'grupoMolestias': {
      'M1': 'Small eye discomfort',
      'M2': 'Eye discomfort',
      'M3': 'Intense eye discomfort',
      'M4': 'Very intense eye discomfort',
      'M5': 'Medium face discomfort',
      'M6': 'Intense medium face discomfort',
      'M7': 'Photophobia',
      'M8': 'Nausea',
    },
    'monthLetters': {
      "01": "Jan",
      "02": "Feb",
      "03": "Mar",
      "04": "Apr",
      "05": "May",
      "06": "Jun",
      "07": "Jul",
      "08": "Aug",
      "09": "Sep",
      "10": "Oct",
      "11": "Nov",
      "12": "Dec",
    },
    'sinmolestias': 'No discomfort',
    'sinotros': 'No other symptoms',
    'sinmedicacion': 'No medication',
    'sinduracion': 'No defined duration',
    'grupoDolor': {
      'D0': 'Light pain',
      'D1': 'Stinging pain',
      'D2': 'Very stinging pain',
      'D3': 'Pain prevents normal life',
    },
    'select': 'Select',
    'fecha': 'Date',
    'listado': 'List',
    'editar': 'edit',
    'gradodolor': 'Pain grade',
    'mismoprocesoanterior': 'Continuation of previous process',
    'molestias': 'Discomfort',
    'otrossintomas': 'Other symptoms',
    'medicacion': 'Medication',
    'duracion': 'Duration',
    'contprocesoanterior': 'Continuation of previous process',
    'yes': 'Yes',
    'no': 'No',
    'next': 'Next',
    'prev': 'Previous',
    'guardar': 'Save',
    'borrar': 'Delete',
    'units': 'hours',
    'mensajeModalBorrar': 'Are you sure you want to delete this record?',
    'mensajeDatosGuardados': 'Data saved successfully',
  },
  'es': {
    'header': header.es,
    'footer': footer.es,
    'title': 'Jáquécastigo',
    'subtitle': 'Cuenta tus jaquecas',
    'grupoMolestias': {
      'M1': 'Pequeña molestia ojo',
      'M2': 'Molestia ojo',
      'M3': 'Molestia intensa ojo',
      'M4': 'Molestia muy intensa ojo',
      'M5': 'Molestia media cara',
      'M6': 'Molestia intensa media cara',
      'M7': 'Fotofobia',
      'M8': 'Nauseas',
    },
    'monthLetters': {
      "01": "Ene",
      "02": "Feb",
      "03": "Mar",
      "04": "Abr",
      "05": "May",
      "06": "Jun",
      "07": "Jul",
      "08": "Ago",
      "09": "Sep",
      "10": "Oct",
      "11": "Nov",
      "12": "Dic",
    },
    'sinmolestias': 'Sin molestias',
    'sinotros': 'Sin otros síntomas',
    'sinmedicacion': 'Sin medicación',
    'sinduracion': 'Sin duración definida',
    'grupoDolor': {
      'D0': 'Dolor leve',
      'D1': 'Dolor punzante',
      'D2': 'Dolor muy punzante',
      'D3': 'Dolor impide hacer vida normal',
    },
    'select': 'Selecciona',
    'fecha': 'Fecha',
    'listado': 'Listado',
    'editar': 'editar',
    'gradodolor': 'Grado de dolor',
    'mismoprocesoanterior': 'Continuación proceso anterior',
    'molestias': 'Molestias',
    'otrossintomas': 'Otros síntomas',
    'medicacion': 'Medicación',
    'duracion': 'Duración',
    'contprocesoanterior': 'Continuacion del proceso anterior',
    'yes': 'Sí',
    'no': 'No',
    'next': 'Siguiente',
    'prev': 'Anterior',
    'guardar': 'Guardar',
    'borrar': 'Borrar',
    'units': 'horas',
    'mensajeModalBorrar': '¿Estás seguro de que quieres borrar este registro?',
    'mensajeDatosGuardados': 'Datos guardados correctamente',
  },
}